apiVersion : apps/v1
kind: Deployment
metadata:
  name: antrahrmapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antrahrmapp
  template:
    metadata:
      labels:
        app: antrahrmapp 
    spec:
      containers:
        - name: antrahrmapp 
          image: hrmimageregistry.azurecr.io/antrahrmapp
          ports:
          - containerPort: 8080